import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer";
import React from "react";
import AnimatedCursor from "react-animated-cursor"





const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
      <div className="text-gray-500">
     
      <Navbar/>
        <main className="min-h-screen  pt-12">
        <AnimatedCursor
        outerStyle={{
          border:"1px solid white"
        }}
    showSystemCursor={true}
    innerSize={14}
    outerSize={70}
    innerStyle={{
      backgroundColor:'white',
      border:'1px solid blue'
    }}
    color="30, 64, 175" 
    outerAlpha={0.1}
    innerScale={0.7}
    outerScale={2}
    clickables={[
      'a',
      'input[type="text"]',
      'input[type="email"]',
      'input[type="number"]',
      'input[type="submit"]',
      'input[type="image"]',
      'label[for]',
      'select',
      'textarea',
      'button',
      '.link',
    ]}
  />            
        {children}
        </main>
        {/* footer  */}
   <div>
    <Footer/>
   </div>
      </div>
    
      </body>
    </html>
  );
}



